server:
  port: 8002
  servlet:
    context-path: /spring-security


#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  packages-to-scan: com.spring.springsecurity
#  paths-to-match: /web/**
#springfox:
#  documentation:
#    enabled: true


springfox:
  documentation:
    swagger-ui:
      enabled: true


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
