server:
  port: 8002
  servlet:
    context-path: /spring-security


#springfox:
#  documentation:
#    swagger-ui:
#      enabled: false

knife4j:
  enable: false
  setting:
    enableVersion: true

# 解决spring2.6以上版本swagger3
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
